builds:
  - binary: compass
    goos:
      - darwin
      - linux
    goarch:
      - amd64

brew:
  name: compass

  github: 
    owner: khoi
    name: homebrew-tap

  folder: Formula

  test: |
    system "#{bin}/program -h"
