name: test
on: [push]
jobs:

  test:
    name: Test on go ${{ matrix.go_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: [ '1.12.x', '1.13.x' ]
        os: [ubuntu-latest, macOS-latest]
        
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go_version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: test
      run: go test -v ./... --race
